# Generated by Django 2.0.2 on 2018-12-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('first_lastname', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('second_lastname', models.CharField(max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
    ]
