# Generated by Django 2.0.2 on 2018-12-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
