# Generated by Django 3.0.2 on 2020-04-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del establecimiento'),
        ),
    ]
