# Generated by Django 2.0.2 on 2018-12-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio unitario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
    ]
