# Generated by Django 2.0.2 on 2019-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181229_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('D', 'Disponible'), ('A', 'Agotado')], default='D', max_length=1, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Máximo 40 caracteres.)'),
        ),
    ]
