# Generated by Django 2.0.2 on 2018-12-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181216_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('N', 'No confirmado'), ('C', 'Confirmado')], default='N', max_length=1, verbose_name='Estado del pedido'),
        ),
    ]
