# Generated by Django 2.0.2 on 2019-01-03 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190103_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='product.Product', verbose_name='Id del producto'),
        ),
    ]
