# Generated by Django 2.0.2 on 2019-01-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190103_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersprod', to='order.Order', verbose_name='Id del pedido'),
        ),
    ]
