# Generated by Django 2.0.2 on 2019-03-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-created'], 'verbose_name': 'Consolidado', 'verbose_name_plural': 'Consolidados'},
        ),
    ]
